### ISSUE TITLE
Here unhandled exception

### ISSUE THREAD

**Issue by Feverqwe** [sarathkcm/TheMovieDBClient#2]
https://github.com/sarathkcm/TheMovieDBClient/blob/2026b418b71654a04042c2c7aff705cbd5c33433/themoviedbclient.js#L77

**Comment by sarathkcm** [comment]
It is working fine for me here:  [https://runkit.com/sarathkcm/59c8f9e41a140b0012bfac96](https://runkit.com/sarathkcm/59c8f9e41a140b0012bfac96)

Could you please share your code? (after removing your API Key from the code, of course).

Also please let me know the node version you are using.

**Comment by Feverqwe** [comment]
I use node 6. And use your module. It work fine, until server response json. Just wrap in try catch.
```javascript
response.on('end', function () {
  try {
    resolve(JSON.parse(res));
  } catch(err) {
    reject(err);
  }
});
```
